version: "3.6"

services: 
  # WEB APP
  web:
    build: .
    ports: 
      - "5000:5000"
    environment: 
      GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET
      FACEBOOK_APP_ID
      FACEBOOK_CLIENT_SECRET
      MONGO_URI
      COOKIE_KEY
      FOOTBALL_API_KEY
      YOUTUBE_API_KEY
      NODE_ENV
    
      # volumes: 
      #   -./:/usr/src/app