export const GET_LEAGUE_DATA = "GET_LEAGUE_DATA";
export const GET_COMPETITION_DATA = "GET_COMPETITION_DATA";
export const GET_TEAM_DATA = "GET_TEAM_DATA";
export const GET_STANDINGS_DATA = "GET_STANDINGS_DATA";
